### ISSUE TITLE
Hello engineer.how can i fix this error?

### ISSUE THREAD

**Issue by S01tani** [dibagaran/cs-2015-7-alpha#2]
![error](https://cloud.githubusercontent.com/assets/13216906/8903247/cebb4d92-346b-11e5-91bf-c1e03f9362c6.PNG)
and my customer class is:
 class customer
    {
        //member variables
        public int CustID;
        public string Name;
        public string Address;

```
    //constructor for initializing fields
    customer()
    {
        CustID = 1101;
        Name = "Tom";
        Address = "USA";
    }
    //method for displaying customer records (functionality)
    public void displayData()
    {
        Console.WriteLine("Customer=" + CustID);
        Console.WriteLine("Name=" + Name);
        Console.WriteLine("Address=" + Address);
    }
    // Code for entry point
}
```

**Comment by meysam-mousavi** [comment]
The class constructor is private because you didn't specify any access modifiers, hence the compiler complains about its protection level. Change your code like this:

``` c#
public customer()
{
    CustID = 1101;
    Name = "Tom";
    Address = "USA";
}
```

We'll discuss constructors at length in future sessions. Keep in mind that it's best practice to start class names with uppercase letters so change 'class customer' to 'class Customer'. Also we start fields with lowercase characters and use meaningful variable names, so change 'CustID' to 'customerID' or 'customerId' and so on ...

Cheers

**Comment by S01tani** [comment]
ok, thank u master.
