### ISSUE TITLE
session 10_UI file_line 59_error

### ISSUE THREAD

**Issue by muhammadbaneshi** [dibagaran/cs-2015-7-alpha#5]
Error   CS0173  Type of conditional expression cannot be determined because there is no implicit conversion between 'Project.Person' and 'Project.Company'

**Comment by AMINEDGE** [comment]
This Error appears when in this type of 'if else' , DataTypes are different, Here you see :

``` javascript
Phonebook.Add (Console.ReadKey (true).Key != ConsoleKey.C ? new Person (Get ("First Name"),
 Get ("Last Name"), Get ("Phone Number"), Get ("Address")) : new Company (Get ("Title"),
 Get ("Phone Number"), Get ("Address")));
```

Person and Company Classes aren't the same datatype so you have to make them the same.
Here is the way I did using TypeCasting:

``` javascript
Phonebook.Add(Console.ReadKey(true).Key != ConsoleKey.C ?
 ((Contact)new Person(Get("First Name"),Get("Last Name"),Get("Phone Number"),
 Get("Address"))) : new Company(Get("Title"),Get("Phone Number"), Get("Address")));
```

And it should work because I cast Person to Contact and Company has inherited from Contact too so now they are the same datatype and the error disappeared.

**Comment by meysam-mousavi** [comment]
You're right, I forgot the cast and I fixed it. Nice catch!

**Comment by muhammadbaneshi** [comment]
this is right form, not that you wrote @AMINEDGE

``` csharp
Phonebook.Add(Console.ReadKey(true).Key != ConsoleKey.C ? (Contact)new Person(Get("First Name"),
 Get("Last Name"), Get("Phone Number"), Get("Address")) : new Company(Get("Title"),
 Get("Phone Number"), Get("Address")));
```

**Comment by meysam-mousavi** [comment]
What @AMINEDGE wrote is correct, it just has some extra parentheses which is harmless.

**Comment by muhammadbaneshi** [comment]
extra parentheses is harmful. if you disagree test it.

**Comment by meysam-mousavi** [comment]
Just to be sure I double checked it using Xamarin Studio on Mac OS X. The code works fine. How come you say the parentheses are harmful? Do you get any errors or something?

**Comment by AMINEDGE** [comment]
@muhammadbaneshi I didn't pay attention to the parentheses because they don't make changes if you know how the code works. I just wanted to solve the problem nothing more, it's depend on you to how to write a code maybe you used to use the least parentheses and extra stuff but it's not the same about everyone. However I think my code doesn't have extra parentheses that much so no problem with that 😉

**Comment by muhammadbaneshi** [comment]
Forget it. I made mistake. Thanks.

**Comment by AMINEDGE** [comment]
It's okay we're here to cure our mistakes and solve the problems.
